server:
  port: 8080
  #ssl:
   # key-store: classpath:ca.jks
   # key-store-password: 7a6b6e0y
   # key-store-type: JKS
spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: shl15718315381@qq.com
    password: wkvqjvovmhylfjhj
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
  # rabbitmq:
  #   addresses: localhost
  #   username: admin
  #   password: admin
  #   virtual-host: /
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
      web-task: 60
    flow:
      period: 5
      limit: 100
      block: 30
  datasource:
    url: jdbc:mysql://localhost:3306/suhualin
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  ai:
    openai:
      api-key: sk-xxxxxxxxxxxxxxxxxxx
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
alipay:
  protocol: xxxxxxxxxxxxxxxxxxx
  gatewayHost: xxxxxxxxxxxxxxxxxxx
  signType: xxxxxxxxxxxxxxxxxxx
  appId: xxxxxxxxxxxxxxxxxxx
  merchantPrivateKey: merchantPrivateKey.txt
  merchantCertPath: xxxxxxxxxxxxxxxxxxx.crt
  alipayCertPath: xxxxxxxxxxxxxxxxxxx.crt
  alipayRootCertPath: xxxxxxxxxxxxxxxxxxx.crt
  notifyUrl: xxxxxxxxxxxxxxxxxxx
frontend:
  articles:
    path: my-project-frontend/src/assets/articles
